import type { DetectedPattern } from "./types";

/**
 * Facts used by the public site.
 *
 * Every claim here is traceable to something in this repository. Nothing is
 * invented: no statistics, no testimonials, no customer logos, no press
 * mentions, no assertions about named competitors. A marketing page for a
 * product whose entire argument is "it never fabricates a record" cannot
 * itself contain a fabricated record.
 *
 * Where a number appears, its source is named in a comment.
 */

/** apps/api/ollama/Modelfile.planora-pro */
export const MODEL = {
  name: "planora-pro",
  base: "qwen3.5:9b",
  runtime: "Ollama",
  endpoint: "127.0.0.1:11434",
  /** PARAMETER lines in the Modelfile. */
  contextTokens: 8192,
  temperature: 0.4,
  /**
   * Stated as a requirement, not as a description of any particular machine.
   * Naming the exact development hardware on a public page identifies its
   * owner without telling a reader anything they can act on.
   */
  hardwareRequirement: "A GPU with about 8 GB of VRAM is enough",
  hardwareNote: "Anything that can serve a 9B model through Ollama will do. Without a GPU the companion falls back to Planora's own planning rules and says so."
} as const;

/** apps/api/src/services/patterns.ts */
export const PATTERN_ENGINE = {
  windowDays: 60,
  minPairedDays: 8,
  minCorrelation: 0.45,
  kinds: ["weekday_rhythm", "time_of_day", "lapse", "co_occurrence", "trend"] as const
} as const;

/**
 * Real output from the pattern engine.
 *
 * Captured from `GET /api/neural/patterns` for the seeded `pattern-fixture`
 * account, which carries 60 days of synthetic history generated by
 * `apps/api/scripts/seed-pattern-fixture.ts`. It is labelled as such wherever
 * it appears — it is a demonstration of the engine, not a real person's data,
 * and presenting it as anything else would be the exact failure this product
 * exists to avoid.
 */
export const SAMPLE_PATTERN: DetectedPattern = {
  kind: "co_occurrence",
  key: "sleep-mood.co_occurrence",
  title: "More sleep the night before tends to coincide with higher mood.",
  detail: "On your higher-sleep days, mood averaged 4 against 2 on lower ones, across 59 days.",
  confidence: 0.85,
  evidence: {
    pearsonR: 1,
    pairedDays: 59,
    lagDays: 1,
    averageWhenHigh: 4,
    averageWhenLow: 2,
    note: "Association only. This is not evidence of cause."
  }
};

export const SAMPLE_TREND: DetectedPattern = {
  kind: "trend",
  key: "stress.trend",
  title: "Stress is falling week over week.",
  detail: "About 0.7/10 per week across 8 weeks. Moving the way you would want.",
  confidence: 0.85,
  evidence: {
    weeklyAverages: [
      { weeksAgo: 7, average: 8.14 },
      { weeksAgo: 6, average: 7.57 },
      { weeksAgo: 5, average: 7 },
      { weeksAgo: 4, average: 6 },
      { weeksAgo: 3, average: 5.43 },
      { weeksAgo: 2, average: 4.86 },
      { weeksAgo: 1, average: 4 },
      { weeksAgo: 0, average: 3.29 }
    ],
    slopePerWeek: -0.7,
    rSquared: 1,
    improving: true
  }
};

/**
 * Also real output. The engine reports the checks that found nothing and why,
 * which is the part most systems hide.
 */
export const SAMPLE_INCONCLUSIVE = [
  { key: "water-energy.co_occurrence", reason: "Only 0 days where both were logged; needs 8." },
  { key: "movement-mood.co_occurrence", reason: "No relationship strong enough to report." },
  { key: "task-completion.weekday_rhythm", reason: "Only 0 logs in 60 days." }
] as const;

/**
 * The consent controls, and what each one actually switches off.
 *
 * Derived from `apps/api/src/services/aiPolicy.ts` and the services that read
 * its flags — not from a marketing description of them.
 */
export const CONSENT_CONTROLS = [
  {
    name: "AI personalization",
    where: "Settings",
    defaultState: "On",
    turnsOff:
      "The companion stops reading your records and answers generically. Personalized suggestions are deactivated, and the learning engine reports itself disabled.",
    code: "aiPolicy.canUsePersonalContext"
  },
  {
    name: "Private AI mode",
    where: "Settings",
    defaultState: "Off",
    turnsOff:
      "Journal entries, mood reflections, sleep notes and chat history stop being used as context, and no new learning records are written at all. Suggestions pause.",
    code: "aiPolicy.canUseSensitiveContext + canPersistLearning"
  },
  {
    name: "Use my profile for personalization",
    where: "Profile",
    defaultState: "Off",
    turnsOff:
      "Life stage, profession, goals, interests, wake and sleep times, height and weight stop reaching the companion and the ranker.",
    code: "PersonalProfile.useForPersonalization"
  },
  {
    name: "Contribute anonymous training rows",
    where: "Profile",
    defaultState: "Off",
    turnsOff:
      "The training export refuses to generate. With it on, the export still strips identity, free text, height and weight, and hashes the participant id.",
    code: "PersonalProfile.allowAnonymousTraining"
  },
  {
    name: "Anonymous product analytics",
    where: "Profile",
    defaultState: "Off",
    turnsOff:
      "Nothing, today. The preference is stored, but no analytics service is connected to this build — so nothing is collected either way.",
    code: "PersonalProfile.allowProductAnalytics"
  }
] as const;

/**
 * What the app is and is not. Taken from PROJECT_COMPLETE_RECORD.txt section
 * 15, which is deliberately explicit about what is not claimed as complete.
 */
export const HONEST_LIMITS = [
  "The learning engine is a transparent local ranker, not a neural network and not self-aware.",
  "The companion is a scoped planning assistant. It is not a general chatbot and not a medical authority.",
  "Local memory is deterministic hashed-token retrieval, not large-model semantic search.",
  "Password reset needs an email provider and returns 501 until one is configured.",
  "Mobile notifications are scheduled locally. There is no remote push service.",
  "Apple Health and Fitness integration is not implemented."
] as const;

export const SITE_NAV = [
  { href: "/features", label: "Features" },
  { href: "/how-it-works", label: "How it works" },
  { href: "/privacy", label: "Privacy" },
  { href: "/about", label: "About" },
  { href: "/faq", label: "FAQ" }
] as const;
